<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="StructuralModel" nsURI="http://www.example.org/edge_Computing"
    nsPrefix="Edge_Computing">
  <eClassifiers xsi:type="ecore:EClass" name="Node" abstract="true" eSuperTypes="#//ModelNode">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="aggregation_factor" lowerBound="1"
        upperBound="2" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"
        defaultValueLiteral="0"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="probability_to_generate_a_command_message"
        lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"
        defaultValueLiteral="0.0"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="service_times" lowerBound="1"
        upperBound="4" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"
        defaultValueLiteral="0"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="CentralNode" eSuperTypes="#//Node">
    <eStructuralFeatures xsi:type="ecore:EReference" name="regional_node" eType="#//RegionalNode"
        eOpposite="#//RegionalNode/central_node"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="RegionalNode" eSuperTypes="#//Node">
    <eStructuralFeatures xsi:type="ecore:EReference" name="local_node" eType="#//LocalNode"
        eOpposite="#//LocalNode/regional_node"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="central_node" eType="#//CentralNode"
        eOpposite="#//CentralNode/regional_node"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="LocalNode" eSuperTypes="#//Node">
    <eStructuralFeatures xsi:type="ecore:EReference" name="location" upperBound="-1"
        eType="#//Location" eOpposite="#//Location/local_node"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="device" eType="#//Device"
        eOpposite="#//Device/local_node"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="regional_node" eType="#//RegionalNode"
        eOpposite="#//RegionalNode/local_node"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Sensor" eSuperTypes="#//Device">
    <eStructuralFeatures xsi:type="ecore:EReference" name="sensortype" eType="#//SensorType"
        eOpposite="#//SensorType/sensor"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Actuator" eSuperTypes="#//Device">
    <eStructuralFeatures xsi:type="ecore:EReference" name="actuatortype" eType="#//ActuatorType"
        eOpposite="#//ActuatorType/actuator"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Network" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EReference" name="router" upperBound="-1"
        eType="#//Router" eOpposite="#//Router/network"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        iD="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="LAN" eSuperTypes="#//Network">
    <eStructuralFeatures xsi:type="ecore:EReference" name="network_type" lowerBound="1"
        eType="#//Network_Type"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="modelnode" eType="#//ModelNode"
        eOpposite="#//ModelNode/lan"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="WAN" eSuperTypes="#//Network">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="delay" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"
        defaultValueLiteral="0.0"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Router">
    <eStructuralFeatures xsi:type="ecore:EReference" name="network" lowerBound="2"
        upperBound="-1" eType="#//Network" eOpposite="#//Network/router"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="delay" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"
        defaultValueLiteral="0.0"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        defaultValueLiteral="0" iD="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Device" abstract="true" eSuperTypes="#//ModelNode">
    <eStructuralFeatures xsi:type="ecore:EReference" name="location" lowerBound="1"
        eType="#//Location" eOpposite="#//Location/device"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="local_node" eType="#//LocalNode"
        eOpposite="#//LocalNode/device"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Location" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EReference" name="device" upperBound="-1"
        eType="#//Device" eOpposite="#//Device/location"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="local_node" upperBound="-1"
        eType="#//LocalNode" eOpposite="#//LocalNode/location"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Grid_Node" eSuperTypes="#//Location">
    <eStructuralFeatures xsi:type="ecore:EReference" name="line" lowerBound="1" upperBound="-1"
        eType="#//Line" eOpposite="#//Line/grid_node"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Section_Component" eSuperTypes="#//Location">
    <eStructuralFeatures xsi:type="ecore:EReference" name="section" lowerBound="1"
        eType="#//Section" eOpposite="#//Section/section_component"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Section">
    <eStructuralFeatures xsi:type="ecore:EReference" name="section_component" lowerBound="1"
        upperBound="-1" eType="#//Section_Component" eOpposite="#//Section_Component/section"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="line" lowerBound="1" eType="#//Line"
        eOpposite="#//Line/section"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Line">
    <eStructuralFeatures xsi:type="ecore:EReference" name="section" lowerBound="1"
        upperBound="-1" eType="#//Section" eOpposite="#//Section/line"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="grid_node" lowerBound="2"
        upperBound="2" eType="#//Grid_Node" eOpposite="#//Grid_Node/line"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Network_Type" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="input_service_times" lowerBound="1"
        upperBound="4" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"
        defaultValueLiteral="0.0"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="output_service_times" lowerBound="1"
        upperBound="4" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"
        defaultValueLiteral="0.0"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Wired" eSuperTypes="#//Network_Type"/>
  <eClassifiers xsi:type="ecore:EClass" name="Wireless" eSuperTypes="#//Network_Type"/>
  <eClassifiers xsi:type="ecore:EClass" name="Manet" eSuperTypes="#//Network_Type"/>
  <eClassifiers xsi:type="ecore:EClass" name="Area">
    <eStructuralFeatures xsi:type="ecore:EReference" name="router" upperBound="-1"
        eType="#//Router" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="network" upperBound="-1"
        eType="#//Network" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="device" upperBound="-1"
        eType="#//Device" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="lowerArea" upperBound="-1"
        eType="#//Area" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Name" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="networknode" upperBound="-1"
        eType="#//ModelNode" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ModelRoot">
    <eStructuralFeatures xsi:type="ecore:EReference" name="area" upperBound="-1" eType="#//Area"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ActuatorType">
    <eStructuralFeatures xsi:type="ecore:EReference" name="actuator" eType="#//Actuator"
        eOpposite="#//Actuator/actuatortype"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="command_service_time" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble" defaultValueLiteral="0.0"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="transition_rate" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble" defaultValueLiteral="0.0"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="command_weight" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt" defaultValueLiteral="0"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SensorType">
    <eStructuralFeatures xsi:type="ecore:EReference" name="sensor" eType="#//Sensor"
        eOpposite="#//Sensor/sensortype"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="telemetry_rate" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble" defaultValueLiteral="0.0"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="transition_rate" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble" defaultValueLiteral="0.0"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ModelNode" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EReference" name="lan" eType="#//LAN" eOpposite="#//LAN/modelnode"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" ordered="false" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString" iD="true"/>
  </eClassifiers>
</ecore:EPackage>
