<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="QueueNetwork" nsURI="http://www.example.org/edge_computing"
    nsPrefix="Edge_Computing">
  <eClassifiers xsi:type="ecore:EClass" name="Queue" eSuperTypes="#//NetworkElement">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="number_of_visits_per_message_type"
        lowerBound="1" upperBound="-1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"
        defaultValueLiteral="0"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="service_time_per_message_type"
        lowerBound="1" upperBound="-1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"
        defaultValueLiteral="0.0"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Root">
    <eStructuralFeatures xsi:type="ecore:EReference" name="area" upperBound="-1" eType="#//Area"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="message" upperBound="-1"
        eType="#//Message" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Delay" eSuperTypes="#//NetworkElement">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="delay_value" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble" defaultValueLiteral="0.0"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="NetworkElement" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EReference" name="sendTo" upperBound="-1"
        eType="#//NetworkElement" eOpposite="#//NetworkElement/receiveFrom"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="receiveFrom" upperBound="-1"
        eType="#//NetworkElement" eOpposite="#//NetworkElement/sendTo"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DataSource" eSuperTypes="#//NetworkElement">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="rates_per_message_type"
        lowerBound="1" upperBound="-1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"
        defaultValueLiteral="0.0"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Area">
    <eStructuralFeatures xsi:type="ecore:EReference" name="networkelement" upperBound="-1"
        eType="#//NetworkElement" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="lowerArea" upperBound="-1"
        eType="#//Area" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Message">
    <eStructuralFeatures xsi:type="ecore:EReference" name="elementsToTraverse" lowerBound="1"
        upperBound="-1" eType="#//NetworkElement"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
</ecore:EPackage>
